### ISSUE TITLE
feat: multiple db support

### ISSUE THREAD

**Issue by damphat** [damphat/kv-bash#15]
```bash
# list all databases, and mark the current database with the '*'
kvuse
    * default-db
      test-1
      todo-app

# switch to todo-app
kvuse todo-app

```

# TODO
- [ ] kvuse switch the current database 
- [ ] kvuse print all database if there no parameter supplied to the kvuse command
- [ ] kvset create the database if it not exists
- [ ] kvclear should also remove database
- [ ] kvlist should print current database name at the top?
- [ ] how to go back to default-db

# Questions
- Q: how to see current database?
- A: `kvuse`
- Q: how to list all databases?
- A: `kvuse`
- Q: how to create database?
- A: `kvuse <db-name>`
- Q: how to delete a database?
- A: `kvuse <db-name>` then `kvclear`
